[package]
name = "ocicrypt-rs"
version = "0.1.0"
description = "the OCI image spec implementation of container image encryption"
repository = "https://github.com/containers/ocicrypt-rs"
readme = "README.md"
license = "Apache-2.0"
authors = ["The ocicrypt Authors"]
edition = "2018"

[dependencies]
anyhow = ">=1.0"
aes = ">=0.8"
base64 = "0.13"
base64-serde = "0.6"
ctr = ">=0.9"
hmac = ">=0.12"
josekit = { version = ">=0.7", optional = true }
lazy_static = ">=1.4"
openssl = { version = ">=0.10", features = ["vendored"] }
pin-project-lite = "0.2.9"
prost = { version = ">=0.11.0", optional = true }
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
sha2 = ">=0.10"
tokio = { version = "1.17.0", features = ["rt-multi-thread"], optional = true }
tonic = { version = ">=0.8.0", optional = true }
attestation_agent = { git = "https://github.com/confidential-containers/attestation-agent", rev = "cbdd744", optional = true  }

[build-dependencies]
tonic-build = {version = "0.8.0", optional = true }

[dev-dependencies]
aes-gcm = { version = "0.10" }

[features]
default = ["keywrap-jwe", "keywrap-keyprovider-cmd"]
eaa_kbc = ["keywrap-keyprovider-native", "attestation_agent/eaa_kbc"]
async-io = ["tokio"]
keywrap-jwe = ["josekit"]
keywrap-keyprovider = []
keywrap-keyprovider-cmd = ["keywrap-keyprovider"]
keywrap-keyprovider-grpc = ["keywrap-keyprovider", "prost", "tonic", "tokio/net"]
keywrap-keyprovider-native = ["keywrap-keyprovider", "tokio/net", "tokio/sync", "attestation_agent"]
gen-proto = ["tonic-build"]
