[package]
name = "ocicrypt-rs"
version = "0.1.0"
description = "the OCI image spec implementation of container image encryption"
repository = "https://github.com/containers/ocicrypt-rs"
readme = "README.md"
license = "Apache-2.0"
authors = ["The ocicrypt Authors"]
edition = "2018"

[features]
default = ["keywrap-jwe","keywrap-keyprovider","utils-runner","utils-keyprovider"]
keywrap-jwe = []
keywrap-keyprovider = []
utils-runner = []
utils-keyprovider = []

[dependencies]
anyhow = ">=1.0"
josekit = ">=0.7"
serde_json = ">=1.0"
serde_derive = ">=1.0"
serde = ">=1.0"
tonic = ">=0.5.0"
prost = "0.9.0"
prost-types = "0.9.0"
aes-gcm = "0.9.2"
ctr = ">=0.1"
rand = ">=0.8"
sha2 = ">=0.9"
hmac = ">=0.12"
aes = { version = ">=0.7", features = ["ctr"] }
base64-serde = "0.6"
base64 = "0.13"
lazy_static = ">=1.4"
oci-distribution = "0.7"
tokio = { version = "1.12.0", features = ["rt-multi-thread"] }

[dev-dependencies]
openssl = ">=0.10"

[build-dependencies]
tonic-build = ">=0.5.1"
