[package]
name = "ocicrypt-rs"
version = "0.1.0"
description = "the OCI image spec implementation of container image encryption"
repository = "https://github.com/containers/ocicrypt-rs"
readme = "README.md"
license = "Apache-2.0"
authors = ["The ocicrypt Authors"]
edition = "2018"

[dependencies]
anyhow = ">=1.0"
aes = ">=0.8"
aes-gcm = { version = "0.9.2", optional = true }
base64 = "0.13"
base64-serde = "0.6"
ctr = ">=0.9"
hmac = ">=0.12"
josekit = { version = ">=0.7", optional = true }
lazy_static = ">=1.4"
oci-distribution = { git = "https://github.com/krustlet/oci-distribution", rev = "1ba0d94a900a97aa1bcac032a67ea23766bcfdef" }
prost = { version = "0.10.0", optional = true }
rand = ">=0.8"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
sha2 = ">=0.10"
tokio = { version = "1.17.0", features = ["rt-multi-thread"], optional = true }
tonic = { version = ">=0.7.0", optional = true }

[dev-dependencies]
openssl = ">=0.10"

[build-dependencies]
tonic-build = {version = ">=0.7.0", optional = true }

[features]
default = ["keywrap-jwe", "keywrap-keyprovider"]
keywrap-jwe = ["josekit"]
keywrap-keyprovider = ["aes-gcm", "tokio", "tonic-build", "utils-runner", "utils-keyprovider"]
utils-runner = []
utils-keyprovider = ["prost", "tonic"]
