// This file is generated by ttrpc-compiler 0.5.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct KeyProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl KeyProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        KeyProviderServiceClient {
            client,
        }
    }

    pub async fn wrap_key(&self, ctx: ttrpc::context::Context, req: &super::keyprovider::keyProviderKeyWrapProtocolInput) -> ::ttrpc::Result<super::keyprovider::keyProviderKeyWrapProtocolOutput> {
        let mut cres = super::keyprovider::keyProviderKeyWrapProtocolOutput::new();
        ::ttrpc::async_client_request!(self, ctx, req, "keyprovider.KeyProviderService", "WrapKey", cres);
    }

    pub async fn un_wrap_key(&self, ctx: ttrpc::context::Context, req: &super::keyprovider::keyProviderKeyWrapProtocolInput) -> ::ttrpc::Result<super::keyprovider::keyProviderKeyWrapProtocolOutput> {
        let mut cres = super::keyprovider::keyProviderKeyWrapProtocolOutput::new();
        ::ttrpc::async_client_request!(self, ctx, req, "keyprovider.KeyProviderService", "UnWrapKey", cres);
    }
}

struct WrapKeyMethod {
    service: Arc<dyn KeyProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for WrapKeyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<(u32, Vec<u8>)> {
        ::ttrpc::async_request_handler!(self, ctx, req, keyprovider, keyProviderKeyWrapProtocolInput, wrap_key);
    }
}

struct UnWrapKeyMethod {
    service: Arc<dyn KeyProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for UnWrapKeyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<(u32, Vec<u8>)> {
        ::ttrpc::async_request_handler!(self, ctx, req, keyprovider, keyProviderKeyWrapProtocolInput, un_wrap_key);
    }
}

#[async_trait]
pub trait KeyProviderService: Sync {
    async fn wrap_key(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _req: super::keyprovider::keyProviderKeyWrapProtocolInput) -> ::ttrpc::Result<super::keyprovider::keyProviderKeyWrapProtocolOutput> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/keyprovider.KeyProviderService/WrapKey is not supported".to_string())))
    }
    async fn un_wrap_key(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _req: super::keyprovider::keyProviderKeyWrapProtocolInput) -> ::ttrpc::Result<super::keyprovider::keyProviderKeyWrapProtocolOutput> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/keyprovider.KeyProviderService/UnWrapKey is not supported".to_string())))
    }
}

pub fn create_key_provider_service(service: Arc<dyn KeyProviderService + Send + Sync>) -> HashMap <String, Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>> {
    let mut methods = HashMap::new();

    methods.insert("/keyprovider.KeyProviderService/WrapKey".to_string(),
                    std::boxed::Box::new(WrapKeyMethod{service: service.clone()}) as std::boxed::Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("/keyprovider.KeyProviderService/UnWrapKey".to_string(),
                    std::boxed::Box::new(UnWrapKeyMethod{service: service.clone()}) as std::boxed::Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods
}
