name: ocicrypt-rs build
on: [push, pull_request, create]

jobs:
  ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: Run cargo build - keywrap-none
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features

      - name: Run cargo build - keywrap-jwe
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=keywrap-jwe

      - name: Run cargo build - keywrap-keyprovider
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=keywrap-keyprovider

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Run cargo test - keywrap-none
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Run cargo test - keywrap-jwe
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=keywrap-jwe

      - name: Run cargo test - keywrap-keyprovider
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=keywrap-keyprovider

      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run rust lint check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
